baseURL = 'https://liliwiki.com/'
languageCode = 'zh-cn'
title = 'LiliWiki - 立里的博客'
theme = 'hugo-theme-stack'
defaultContentLanguage = 'zh'

paginate = 10
hasCJKLanguage = true

[params]
    mainSections = ['post']
    featuredImageField = 'image'
    rssFullContent = true
    favicon = 'img/avatar.jpg'
    description = '立里博客 (LiliWiki) - 立里的个人博客，分享技术文章与资源。立里blog，技术笔记与教程分享站。'

[params.footer]
    since = 2025

[params.dateFormat]
    published = '2006-01-02'
    lastUpdated = '2006-01-02 15:04'

[params.sidebar]
    emoji = ''
    subtitle = '个人博客 & 资源分享'
    avatar = 'img/avatar.jpg'

[params.article]
    math = false
    toc = true
    readingTime = true

[params.article.license]
    enabled = false

[params.comments]
    enabled = true
    provider = ""

[[params.widgets.homepage]]
    type = 'search'

[[params.widgets.homepage]]
    type = 'archives'

[[params.widgets.page]]
    type = 'toc'

[params.colorScheme]
    toggle = true
    default = 'auto'

[menu]

[[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1
    [menu.main.params]
        icon = 'home'

[[menu.main]]
    identifier = 'archives'
    name = '归档'
    url = '/archives/'
    weight = 2
    [menu.main.params]
        icon = 'archives'

[[menu.main]]
    identifier = 'search'
    name = '搜索'
    url = '/search/'
    weight = 3
    [menu.main.params]
        icon = 'search'

[[menu.main]]
    identifier = 'download'
    name = '下载站'
    url = 'https://download.liliwiki.com/'
    weight = 4
    [menu.main.params]
        icon = 'link'

[[menu.main]]
    identifier = 'login'
    name = '账号'
    url = 'https://auth.liliwiki.com/login'
    weight = 5
    [menu.main.params]
        icon = 'user'

[[menu.main]]
    identifier = 'writer'
    name = '写作'
    url = 'https://auth.liliwiki.com/write'
    weight = 6
    [menu.main.params]
        icon = 'messages'

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup]
[markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    style = 'monokai'

[markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2

[markup.goldmark.renderer]
    unsafe = true

[related]
    includeNewer = true
    threshold = 60
    toLower = false

[[related.indices]]
    name = 'tags'
    weight = 100

[[related.indices]]
    name = 'categories'
    weight = 200
